### ISSUE TITLE
Filter errors with latest version

### ISSUE THREAD

**Issue by davidpede** [modxcms/pThumb#14]
I have just upgraded to the latest verision (2.2.1) and there are problems with filters. The image gets generated in the correct cache folder and displays on the website all fine. However the filters (&fltr) I use are not being implemented.

My code:
[[+tv.image:pthumb=`w=75&h=105&far=0&dpi=72&q=95&fltr=usm|60|0.8|3`]]

Error:
(ERROR @ /foo/core/model/phpthumb/phpthumb.class.php : 1498) PHP warning: Invalid argument supplied for foreach()

Version 2.1.0-pl2 works fine. The filters are implemented and there are no errors in the Log.

**Comment by oo12** [comment]
Thanks; I'll take a look at this in the next day or two and get it fixed.

**Comment by oo12** [comment]
Fixed in 2.2.2-pl.  I'm really glad you reported this one!
