### ISSUE TITLE
Boolean custom data attributes given empty value after conversion (no longer boolean)

### ISSUE THREAD

**Issue by watou** [modxcms/pThumb#15]
If you push `<span data-magic>text</span>` through imageSlim, it comes out `<span data-magic="">text</span>` which can confuse JavaScript code.  Boolean custom data attributes are considered legitimate HTML5.  See http://dev.w3.org/html5/spec/Overview.html#boolean-attribute .

**Comment by watou** [comment]
I will have to investigate further before anyone should look at this.

**Comment by oo12** [comment]
If you want to reopen this, open it under imageSlim :-)

This comes back to the XML/HTML5 differences.  PHP doesn't have a built-in HTML5 parser so imageSlim uses the XML one, which for the most part works just fine.  _But_, there are a few edge cases like this one.  XML doesn't know anything about boolean attributes.

It seems like a pretty obscure thing, one that most people wouldn't ever come across.
What I would do is, right after line 278 in the snippet:

```
$output = str_replace('&#13;', '', substr($dom->saveXML($dom->documentElement), 12, -14) );  // existing line 278
$output = str_replace('data-magic=""', 'data-magic', $output);  // insert this line
```

Not exactly elegant, but it's simple and does the trick.  If you have multiple attributes, the first two arguments to str_replace can be arrays.

**Comment by watou** [comment]
Oops for opening this in the wrong place to begin with, and thanks for offering that explanation and workaround.  I think that if the docs explain the practical effect of the XML vs. HTML5 issue, and offer workarounds like this, then that would be the reasonable limit of what anyone would expect of imageSlim.  Again, thanks for your great contributions.
