### ISSUE TITLE
Image path not working correctly on new version of pthumb

### ISSUE THREAD

**Issue by flinx777** [modxcms/pThumb#16]
We're building a modx site in a subdirectory using pthumb and in the past it worked just fine.  We just upgraded to the newest version (2.2.2-pl) and it broke the image path on the page.  We backed pthumb back to an older version (2.1.0) and the problem no longer occurred.

The problem is with relative paths.

So, usually the cache generated image path should be like this:

http://site-ip-address/sub-directory-name/assets/components/phpthumbof/cache/blog-image.1cb372c3723d3bff2c4ba57824eb4507.jpg

where the modx base directory is there /sub-directory-name/

what happens on the latest version is that, the path generated is this:

http://site-ip-address/assets/components/phpthumbof/cache/blog-image.1cb372c3723d3bff2c4ba57824eb4507.jpg

it went outside the modx base directory /sub-directory-name/ .. as you can see, /sub-directory-name/ is not on the path anymore so the images don't load.

I'm not sure if it makes a difference or not, but we are using the old phpthumb call:

[[+tv.product_image:phpthumbof=`w=220&h=160&zc=1`]]

**Comment by oo12** [comment]
Looks like I broke the "MODX in a subdirectory" fix when I added back the [cache_url setting](https://github.com/oo12/phpThumbOf/issues/8).

This should fix it though.  With version 2.2.2 installed, replace core/components/phpthumbof/model/phpthumbof.class.php with [this version](https://raw.github.com/oo12/phpThumbOf/pThumb-dev/core/components/phpthumbof/model/phpthumbof.class.php).

**Comment by oo12** [comment]
I updated the package on the MODX provider. Version 2.2.2-pl2 has this fix included.

**Comment by smashbrand-kris** [comment]
We'll implement it and give it a try to see how it goes.  Thanks for fixing that so quickly.
