### ISSUE TITLE
Cannot install via Package Management

### ISSUE THREAD

**Issue by digitalbricks** [modxcms/pThumb#22]
Using MODX 2.2.14-pl i am not able to install this extra via package management. When i click the install button, the "console running ..." message appears but nothing further. If i close this window the extra seems to be installed but it isn't. If i click remove the console claims that no files where found for removing.

**Comment by oo12** [comment]
Can you check your PHP error log and see if there's anything relevant in there?

**Comment by digitalbricks** [comment]
That's curious: I had PHP error logging of. So i enabled it now and retried to install pThumb via package management – and now it works ... Don't know what was wrong before. Think you can close this ticket. Have nice sunday!

**Comment by oo12** [comment]
Strange... Well, glad you got it working!
