### ISSUE TITLE
whong image path

### ISSUE THREAD

**Issue by veqlargh** [modxcms/pThumb#24]
I have this call 

<img src="[[++assets_url]]images/products/[[+catalogue_product_image:phumb=`w=263&h=314&zc=1`]]"/>

in settings I have Images Base Directory set to assets/images/products/

I get this message in error log

[2014-06-24 12:49:17](ERROR @ /index.php) [pThumb] Resource: 2 || Image: (none)
File not found: /home/artisant/public_html/batic/artisan_wine_batic_rose.jpg  **\* Skipping ***

**Comment by oo12** [comment]
I replied to your [thread](http://forums.modx.com/thread/88392/phpthumbof-not-working?page=2#dis-post-501407) on the forums.  _Images Base Directory_ only controls how much of the path is stripped off the front when creating cache file names for the pThumb cache.  It's not added to input paths.  The correct place to do that is in a media source assigned to the TV.
