### ISSUE TITLE
Error on 2.3 Upgrade

### ISSUE THREAD

**Issue by hephaestoskin** [modxcms/pThumb#25]
I get the following when when upgrading a site to Modx 2.3 that utilizes pThumb and it kills the page.
Fatal error: Cannot redeclare phpthumb::__destruct() in /home/ties/public_html/core/model/phpthumb/phpthumb.class.php on line 254

**Comment by oo12** [comment]
I think phpThumb is (semi) broken in 2.3.  You could try using Resizer
instead; that would probably avert the problem.

**Comment by hephaestoskin** [comment]
Garret Overstreet found the issue and solution:
https://github.com/modxcms/revolution/issues/11700

**Comment by le-genda** [comment]
pThumb doesn't work like filters with tv 
this modxcms/revolution#11700 is no solves problem

**Comment by le-genda** [comment]
@hephaestoskin, you can fix pThumb work as a filter in the modx 2.3?
