### ISSUE TITLE
Error on 2.3 Upgrade

### ISSUE THREAD

**Issue by le-genda** [modxcms/pThumb#26]
pThumb doesn't work like filters with tv 
this https://github.com/modxcms/revolution/issues/11700 is not solves problem

**Comment by le-genda** [comment]
I apologize, your extension works. This is wrong I tested it. https://github.com/modxcms/revolution/issues/11700 - it helps

**Comment by oo12** [comment]
MODX 2.3.1 fixes the problem with phpThumb.
