### ISSUE TITLE
Replacement of basepath to URL breaks static usage

### ISSUE THREAD

**Issue by CyntaxDotDev** [modxcms/pThumb#30]
When passing a custom cache URL, i.e. a static url, the str_replace replaces only the start of the URL, but appends the directory twice.

i.e, http://domain.com/static/cache/ thus /home/.../static/cache/ is replaced by http://domain.com/static/cache/static/cache.

**Comment by CyntaxDotDev** [comment]
To add, I've added 2 System Settings, namely "pthumb.ptcache_location" and "pthumb.use_ptcache" as 0. Additionally, I modified the code to return it to phpThumbOf default behavior:

On line 49 I added:

```
$cacheurl = rtrim($modx->getOption('phpthumbof.cache_url', null, $modx->getOption('base_url', null, MODX_BASE_URL), true), '/');
$this->config['cachePathUrl'] = str_replace(MODX_BASE_PATH, "$cacheurl/", $this->config['cachePath']);
```

...and of 54 I added:

```
$this->config['cachePathUrl'] = $modx->getOption('phpthumbof.cache_url', null, TRUE);
```

And I replaced

```
$this->config['cacheNotWritable'] = false;
$cacheurl = rtrim($modx->getOption('phpthumbof.cache_url', null, $modx->getOption('base_url', null, MODX_BASE_URL), true), '/');
$this->config['cachePathUrl'] = str_replace(MODX_BASE_PATH, "$cacheurl/", $this->config['cachePath']);
```

by

```
$this->config['cacheNotWritable'] = false;
```

This will once again support static subdomain usage across our sites.

**Comment by oo12** [comment]
Yes, the cache_url setting simply prepends its value to the thumbnail's path.

In your first post, if you get set cache_url to `http://domain.com/static/cache/` and get `http://domain.com/static/cache/static/cache` then couldn't you instead set cache_url to `http://domain.com/` and end up with what you're after?

**Comment by sepiariver** [comment]
@ReSpawN is this still an issue given the most recent comment?
