### ISSUE TITLE
ImageMagick for MODX

### ISSUE THREAD

**Issue by mindeffects** [modxcms/pThumb#31]
Hi oo12,
this is more a "meta" or "mega" issue: :-D
Do you see a way of integrating **ImageMagick** into MODX? Something like "_passing the parameters over to IM and store the returning image in the MODX cache_" – or an MODX-IM cache like pThumb does it.
I came up with this idea because I wanted to use _blend modes_ which are not available in PhpThumb. IM can do it (http://www.imagemagick.org/Usage/compose/) and a lot more cool stuff.
Also IM knows how to handle _CMYK-PDFs_, which, you remember, is something where _Resizer_ struggles with.
I would be happy if we could talk/chat about this. Interested?

cheers
Oliver
_MODX AMB Cologne, DE_

**Comment by sepiariver** [comment]
@mindeffects sorry with this comment, are you talking about the MODX Core? If so, could you kindly please close this issue and post it in the [Revo](https://github.com/modxcms/revolution/issues) repo?

If you're talking about pThumb... I think it already does support ImageMagick but maybe I'm wrong.

**Comment by mindeffects** [comment]
Is there a follow up repo for pThumb? All other MODX "*thumb*" seem to be abandoned.
