### ISSUE TITLE
Abstract media sources into controllers

### ISSUE THREAD

**Issue by goldsky** [modxcms/pThumb#34]
We have plenty of media sources now (other than Amazon S3), google cloud, dropbox, etc.

It would be great if we can use the controller by media source, rather than bolt the media source in the main class.

I'd be glad to help you on google cloud integration, but we need to refactor the **phpThumbOf** class.

What do you think?

**Comment by oo12** [comment]
You're welcome to work on that if you want to, sure!
I'm not doing much MODX development these days and this isn't something I personally have a need for, but I'd be happy for you to use as much of my existing code as is useful.

**Comment by sepiariver** [comment]
@goldsky did you end up doing anything on this?

**Comment by goldsky** [comment]
@sepiariver no.
turned out, I just needed to set the file with its complete url, and this extra [streamed it down](https://github.com/modxcms/pThumb/blob/pThumb-dev/core/components/phpthumbof/model/phpthumbof.class.php#L179) to process further.

Btw, I didn't realize that this is now under modxcms.
Good to know!

**Comment by sepiariver** [comment]
Yes @goldsky it was dormant so we volunteered to maintain it, not that we have a lot of time on our hands LOL
