### ISSUE TITLE
weird image dimension issue

### ISSUE THREAD

**Issue by hcanning2014** [modxcms/pThumb#36]
Re pthumb
Hi,
I have a jpeg image (1920*956) that if I upload it using a Migx TV it causes the frontend template to render blank. If I upload any other image with that exact dimension it uploads fine and renders fine on the template. Why would some images cause phpthumbof or pthumb to malfunction. Do some jpegs carry extra data or something. Weirdest thing ever. 
Thanks

**Comment by vierkantemeter** [comment]
Some thoughts;
- Is the image in CMYK color mode? (Should be RGB in most cases)
- Does the image has a resolution of 300dpi (or more)? (Should be 72dpi in most cases)
- What happens if you 'resave' the image as JPG in an image editor, and upload it again?

**Comment by sepiariver** [comment]
@hcanning2014 any thoughts on this? Is it still occurring? Depending on your server environment, a large file can cause PHP to run out of memory or timeout, which can manifest as a blank screen—maybe this was the case?
