### ISSUE TITLE
Zoom Crop does not work

### ISSUE THREAD

**Issue by dopeless** [modxcms/pThumb#39]
Hi, can not get zc to work

If I use phpthumb with small vertical image, it's zoomed, but not cropped. If i use resizer, it has richt aspect ratio, bat smallar as it should be...

**Comment by dopeless** [comment]
should add aoe=1, close pls, sry

**Comment by rthrash** [comment]
Hi @dopeless … just to confirm it's OK to close this issue. If not just reply and I'll open it back up.

**Comment by azeller** [comment]
Actually I can reproduce this issue and I am not able to fix it with output enlargement. I am however using pthumb from within Image+, passing along the parameter.
An image of 1150x400 is all squeezed up when I scale it to 400x400. All the others seem to work fine, or the mismatch of aspect ratio is so minor that I can't tell
