### ISSUE TITLE
Snippet-Call doesn't work, but Output-Modifier works

### ISSUE THREAD

**Issue by sebastian-marinescu** [modxcms/pThumb#41]
Hi pThumb-Team, 

I was having a weird issue with pThumb. Using this call: 

```
[[!pthumb? &input=`[[+url]]` &options=`w=300&h=200&zc=C`]]
```

the image got only resized in width, **but not in the height**. 
But using the Output-Modifier works as expected:

```
[[+url:phpthumbof=`
        &w=320
        &h=200
        &zc=C
`]]
```

I never had this issue before and the Snippet-Call-Version always worked, until today.

Maybe relevant: I used it in a ContentBlocks-Field. But actually it shouldn't be relevant, because the same behavior occurred in a simple content. 

My Environment-Specifications: 
- MODX Revolution 2.4.3-pl
- pThumb 2.3.3-pl
- resizer 1.0.1-pl
- PHP Version 5.6.19-nmm1
- imagick module version    3.1.2
- GD Version bundled (2.1.0 compatible)

I tried with and without using resizer. I also tried the different Preferred Graphics Library - Settings.
And what bugs me: Nothing in the error-logs. 

Can someone reproduce this issue?

**Comment by amitpatil321** [comment]
I know this is old post but hope this helps sompne. 
Its because your url could be a web url instead path on file system

[https://forums.modx.com/thread/89978/problem-outputting-image-with-phpthumbof-and-runsnippet](url)

**Comment by sebastian-marinescu** [comment]
Thank you very much for that finding and explanation!
