### ISSUE TITLE
phpThumbOf or pThumb for PDF thumbnails

### ISSUE THREAD

**Issue by tjventurini** [modxcms/pThumb#46]
I'm using phpThumbOf on my site to generate resized images on my modx site. Now I tried to do a download area where I want to show some thumbnails of PDFs, but its not generating them. When I try to use pThumb, it returns the sourcefile path.

I already confirmed, that ImageMagick and php-imagick are installed and enabled.

Also my [local development environment](https://github.com/tjventurini/modxvm) should allow to use exec so I can't see why this isn't working.

Did someone got this to work already?

**Comment by achterbahn** [comment]
The underlying phpThumb would be able to generate PDF-Thumbnails, but I never figured out how to get it to work.
I made a snippet to test if the installed imagemagick (and ghostscript) is working.
Snippetname: generatePDF
```
<?php
$pathparts =pathinfo($input);
$fn = $pathparts['filename'];
$pt = $pathparts['dirname'];
$im = new imagick( $input.'[ 0]' ); 
 
$im->setImageColorspace(255);
$im->setCompression(Imagick::COMPRESSION_JPEG);
$im->setCompressionQuality(60);
$im->setImageFormat('jpeg');
 
$im->writeImage($pt.'/'.$fn.'.jpg');
$im->clear();
$im->destroy();
```

Usage: `[[generatePDF? &input='test.pdf'`

It generates a jpg thumbnail from the PDF. So it would work. 

Would be great, when pThumb oder phpthumbof would support this feature.

**Comment by bwente** [comment]
Try turning off Resizer.

`<img src="[[pthumb? &input=`[[+file]]` &options=`&w=150&h=175&sfn=1&f=jpg` &useResizer=`0`]]">`

**Comment by sepiariver** [comment]
> Try turning off Resizer.
> 
> `<img src="[[pthumb? &input=`[[+file]]` &options=`&w=150&h=175&sfn=1&f=jpg` &useResizer=`0`]]">`

That should actually do it. Resizer does not currently support generating thumbnails of PDFs, as I understand it.
