### ISSUE TITLE
I have problem with to save cache in to subdomain

### ISSUE THREAD

**Issue by Oviraptor83** [modxcms/pThumb#58]
Hello, sorry for my english if I will writing incorrect.

I'll like to do to saving all cache the images in to subdomain.
How I can to do it?

Regards by Alexander.

**Comment by davidpede** [comment]
To serve the cached images from a sub-domain we do the following:

- setup `cache.domain.com` to point at the web root in cPanel/plesk
- create `/img/cache` folders in web root
- In modx sys settings change:
-- `phpthumbof.cache_url` to `https://cache.domain.com/`
-- `pthumb.ptcache_location` to `img/cache`
-- `pthumb.use_ptcache` to `Yes`

The cached imgs will now be served like: https://cache.domain.com/img/cache/image.hash.jpg

We do it like this as you can't use absolute paths for the cache location, must be relative. See #35 for info

**Comment by Oviraptor83** [comment]
How I understood to me need create a sub-domain in root folder of main domain?
But if I using sub-domain in ispManager  and I have this folder list:
\var\www\user\data\www\domain.xx\ main domain
\var\www\user\data\www\sub.domain.xx\ sub-domain

**Comment by davidpede** [comment]
I don't know ispManager at all but https://web-stydia.com/en/kak-dobavit-poddomen-v-cherez-ispmanager/ shows you can create a sub-domain in root folder of main domain: "The second option "Auto subdomains WWW domain subdirectory""

**Comment by Oviraptor83** [comment]
Thanks I will be read this information.

**Comment by Oviraptor83** [comment]
I did it, now this working, thank you very much.
