### ISSUE TITLE
Webp Support

### ISSUE THREAD

**Issue by shatteredsite** [modxcms/pThumb#61]
The ability to export webp image format, lossy or lossless by choice, with alpha for transparency supported. With google speed rankings now taking this into account, it would be extremely useful.

**Comment by sepiariver** [comment]
Unfortunately updating the Imagine dependency past 0.x to support webp means breaking changes and even then not full support. There’s a branch `imagine-122` where work has been started here: https://github.com/sepiariver/Reductionist/tree/imagine-122
