### ISSUE TITLE
Cache URL

### ISSUE THREAD

**Issue by davidpede** [modxcms/pThumb#8]
Don't know if I'm missing somthing but I'd like to be able to control the url of the cache folder. You could do this in phpthumbof using the setting 'phpthumbof.cache_url'. Using pthumb I can only see the 'phpthumbof.cache_path' setting.

I have multiple sub domains, setup using contexts. The images are stored in one of the contexts and I'd like to be able to use them, via pthumb, across all the contexts using the absolute url.

Is this possible with pthumb or is there a better way of doing it?

**Comment by oo12** [comment]
It's not going to do that currently, but I'll try to add this feature back this weekend.  I remember that cache_url setting; I couldn't think of why it would need to be different than MODX_BASE_URL. Now I see though.

So each of your contexts are putting cached images into the same directory on the server, but you want, say, the URL for a resized image on x.site.com to be y.site.com/cache/image.jpg. Something like that?

**Comment by oo12** [comment]
This setting is back now in v2.2.0.  Thanks for letting me know somebody does use it!

**Comment by davidpede** [comment]
That's great, thanks for addressing so quickly!
