### ISSUE TITLE
.pl in a filename causes pThumb to output nothing

### ISSUE THREAD

**Issue by zaigham** [modxcms/pThumb#9]
Please see this line straight from the Error Log:
`[2013-11-08 14:15:16] (ERROR @ /index.php) [pThumb] Resource: 598 || Image: /home/USER/public_html/assets/images/thumbnails/domain.pl.jpg`

Kindly advise.

**Comment by oo12** [comment]
There shouldn't be anything special about a .pl in the filename that would cause things to not work.  Can you check that there is a file domain.pl.jpg in assets/images/thumbnails/?  My guess is that there isn't...
I just made an image with that same name and relative path and it's working fine.

One other thing to look at:  if pThumb can't find a file or can't make a thumbnail for some reason, it returns the input URL unchanged (and puts a message in the error log).  So if you're getting a broken image on the page, probably the original file is missing or the URL is wrong.  Another easy way to check is, if you have something like `[[*image:pthumb=`w=200`]]` change it temporarily to simply `[[*image]]`.  Once you get the image to show up, add back the output filter and things _should_ work.

**Comment by oo12** [comment]
Actually I think the problem must be something else; it looks like it's finding that file ok in fact.  Are there any lines directly below that one in the error log?  Usually there will be.
And how did you figure out the .pl is causing the problem? If you rename the file to domain.jpg will that work?

**Comment by zaigham** [comment]
You are right, problem seems to be somewhere else. I have checked the file system and the images are there, but they don't showup.

I looked into my plain phpthumb install and it works alright. So I am guessing its something with my MODX install?

Can you give me some pointers to look into?

Thanks.

**Comment by oo12** [comment]
You should only see a message in the error log like that—a single line, not followed by any debug info from phpThumb or Resizer—under these conditions:
- You have debug output turned on for pThumb.
- There's already a thumbnail in the cache for that image.

It's just an informational message, not an error.  If the thumbnail wasn't cached, that line would be followed by a bunch of debug output from the graphics library, or some additional error message, for instance that the file wasn't found. If it's already cached though, you just get that single line with the Resource id and the input filename.

That message isn't very explanatory though, come to think of it.  In the next version that message will explicitly say "Loaded from cache" along with the cache URL, so it's clear what's going on.

Check the thumbnail cache; is that image already in there?

**Comment by oo12** [comment]
Are you using contexts by chance?  I mean, besides the default web context.

**Comment by oo12** [comment]
I'm going to close this, but please reopen if it continues to be a problem.
